/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.scoping;

import com.program_in_chinese.quan6.scoping.AbstractQuan6ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Quan6ScopeProvider extends AbstractQuan6ScopeProvider {
}
