/*
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.parser.antlr;

import com.google.inject.Inject;
import com.program_in_chinese.quan6.parser.antlr.internal.InternalQuan6Parser;
import com.program_in_chinese.quan6.services.Quan6GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Quan6Parser extends AbstractAntlrParser {

	@Inject
	private Quan6GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQuan6Parser createParser(XtextTokenStream stream) {
		return new InternalQuan6Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Quan6";
	}

	public Quan6GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Quan6GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
