/*
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Quan6AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/program_in_chinese/quan6/parser/antlr/internal/InternalQuan6.tokens");
	}
}
