/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.quan6.impl;

import com.program_in_chinese.quan6.quan6.Property;
import com.program_in_chinese.quan6.quan6.Quan6Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PropertyImpl extends FeatureImpl implements Property
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Quan6Package.Literals.PROPERTY;
  }

} //PropertyImpl
