/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.quan6;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.program_in_chinese.quan6.quan6.Quan6Package#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
