/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.quan6;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xtype.XImportSection;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quan6</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.program_in_chinese.quan6.quan6.Quan6#getImportSection <em>Import Section</em>}</li>
 *   <li>{@link com.program_in_chinese.quan6.quan6.Quan6#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.program_in_chinese.quan6.quan6.Quan6Package#getQuan6()
 * @model
 * @generated
 */
public interface Quan6 extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Import Section</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Section</em>' containment reference.
   * @see #setImportSection(XImportSection)
   * @see com.program_in_chinese.quan6.quan6.Quan6Package#getQuan6_ImportSection()
   * @model containment="true"
   * @generated
   */
  XImportSection getImportSection();

  /**
   * Sets the value of the '{@link com.program_in_chinese.quan6.quan6.Quan6#getImportSection <em>Import Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Section</em>' containment reference.
   * @see #getImportSection()
   * @generated
   */
  void setImportSection(XImportSection value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.program_in_chinese.quan6.quan6.AbstractElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.program_in_chinese.quan6.quan6.Quan6Package#getQuan6_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // Quan6
