/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6;

import com.program_in_chinese.quan6.Quan6StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Quan6StandaloneSetup extends Quan6StandaloneSetupGenerated {
  public static void doSetup() {
    new Quan6StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
