/*
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Quan6StandaloneSetup extends Quan6StandaloneSetupGenerated {

	def static void doSetup() {
		new Quan6StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
