/*
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Quan6RuntimeModule extends AbstractQuan6RuntimeModule {
}
