/*
 * generated by Xtext 2.13.0
 */
package org.example.domainmodel.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DomainmodelScopeProvider extends AbstractDomainmodelScopeProvider {

}
