/**
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.validation;

import com.program_in_chinese.quan6.validation.AbstractQuan6Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Quan6Validator extends AbstractQuan6Validator {
}
