/*
 * generated by Xtext 2.13.0
 */
package com.program_in_chinese.quan6.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractQuan6ScopeProvider extends XbaseBatchScopeProvider {
}
